Repository TripInfoWeb/solitour-mobile, pull requests merged in 2025-02, with the labels that each got.

#45 Feat: 내 여행 목록 조회 기능
  src/App.tsx
  src/components/common/BottomTabs.tsx
  src/components/skeleton/tour/TourItemListSkeleton.tsx
  src/components/skeleton/tour/TourItemSkeleton.tsx
  src/components/survey/result/detail/SurveyBottomSheetModal.tsx
  src/components/survey/result/detail/SurveyDayList.tsx
  src/components/survey/result/detail/SurveyKakaoMap.tsx
  src/components/survey/result/detail/SurveyPlaceItem.tsx
  src/components/tour/TourItem.tsx
  src/components/tour/TourItemList.tsx
  src/components/tour/TourKakaoMap.tsx
  src/hooks/auth/useSignIn.ts
  src/hooks/survey/result/usePlanSave.ts
  src/hooks/tour/useTourItemList.tsx
  src/screens/TourScreen.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/tour/TourDetailScreen.tsx
  src/screens/tour/TourScreen.tsx
  src/types/navigation.ts
  src/types/plan.ts
  tailwind.config.js
Labels: Design, Feat

#46 Feat: 여행 콘텐츠 다중 선택 기능
  src/assets/common/delete-icon.png
  src/assets/common/menu-icon.png
  src/components/diary/list/DiaryCardMenu.tsx
  src/components/survey/content/SurveyContentItemList.tsx
  src/components/survey/result/detail/SurveyKakaoMap.tsx
  src/components/tour/TourItem.tsx
  src/components/tour/TourItemMenu.tsx
  src/components/tour/TourKakaoMap.tsx
  src/screens/HomeScreen.tsx
  src/screens/survey/SurveyContentScreen.tsx
  src/screens/survey/SurveyDayScreen.tsx
  src/screens/survey/SurveyLoadingScreen.tsx
  src/screens/survey/SurveyThemeScreen.tsx
Labels: Feat, Refactor

#47 Feat: 액세스 토큰 재발급 기능
  src/components/diary/list/DiaryCard.tsx
  src/components/diary/list/DiaryCardList.tsx
  src/components/diary/list/DiaryCardMenu.tsx
  src/components/diary/update/DiaryUpdateEditor.tsx
  src/components/tour/TourItemMenu.tsx
  src/hooks/auth/useSignIn.ts
  src/hooks/auth/useUserInfo.ts
  src/hooks/diary/editor/useDiaryEditor.ts
  src/hooks/diary/list/useDiaryDelete.ts
  src/hooks/diary/list/useDiaryList.ts
  src/hooks/diary/register/useDiaryRegister.ts
  src/hooks/diary/update/useDiaryUpdate.ts
  src/hooks/survey/content/useSurveyContentItemList.ts
  src/hooks/survey/result/usePlanSave.ts
  src/hooks/tour/useTourItemDelete.tsx
  src/hooks/tour/useTourItemList.tsx
  src/libs/getNewAccessToken.ts
  src/screens/MypageScreen.tsx
  src/screens/auth/AuthLoadingScreen.tsx
  src/screens/auth/AuthScreen.tsx
  src/screens/diary/DiaryUpdateScreen.tsx
  src/types/diary.ts
  src/types/navigation.ts
Labels: Feat, Refactor

#51 Feat: 닉네임 변경 기능 & 마이페이지 UI 구현
  src/components/common/BottomTabs.tsx
  src/components/diary/editor/date/DiaryDateBottomSheetModal.tsx
  src/components/diary/editor/date/DiaryDatePicker.tsx
  src/components/diary/editor/feeling/DiaryFeelingBottomSheetModal.tsx
  src/components/diary/editor/feeling/DiaryFeelingPicker.tsx
  src/components/diary/editor/location/DiaryLocationBottomSheetModal.tsx
  src/components/diary/editor/location/DiaryLocationPicker.tsx
  src/components/diary/list/DiaryCardMenu.tsx
  src/components/diary/list/DiaryPageIndicator.tsx
  src/components/diary/register/DiaryRegisterButton.tsx
  src/components/diary/update/DiaryUpdateButton.tsx
  src/components/mypage/MypageItem.tsx
  src/components/mypage/MypageNicknameModal.tsx
  src/components/mypage/MypageProfile.tsx
  src/components/tour/TourItemMenu.tsx
  src/constants/color.ts
  src/hooks/auth/useUserInfo.ts
  src/hooks/mypage/useNicknameModal.ts
  src/libs/zod/NicknameSchema.ts
  src/screens/auth/AuthLoadingScreen.tsx
  src/screens/diary/DiaryEditorScreen.tsx
  src/screens/mypage/MypageScreen.tsx
  src/types/user.ts
Labels: Design, Feat, Refactor

#54 Fix: 여행일기 수정 시 날짜가 변경되는 오류 수정 & 뒤로가기 미동작 오류 수정 & 일기 글 내용 미표시 오류 수정
  src/components/diary/list/DiaryCard.tsx
  src/components/diary/update/DiaryUpdateEditor.tsx
  src/hooks/common/useBackHandler.ts
  src/hooks/diary/editor/useDiaryEditor.ts
  src/types/diary.ts
Labels: Fix

#55 Docs: README.md 작성
  README.md
Labels: Docs

#64 Design: 여행 기간 재설정 & 여행지 카테고리 표시 & 여행 기간 표시 & "테마 여행 추천"으로 변경
  src/App.tsx
  src/components/skeleton/tour/TourItemSkeleton.tsx
  src/components/survey/result/detail/SurveyPlaceItem.tsx
  src/components/tour/TourItem.tsx
  src/constants/color.ts
  src/screens/HomeScreen.tsx
  src/screens/survey/SurveyDayScreen.tsx
  tailwind.config.js
Labels: Design, Feat

#65 Feat: 여행 계획 삭제 기능
  src/components/diary/list/DiaryCardMenu.tsx
  src/components/tour/TourItemMenu.tsx
  src/hooks/tour/useTourItemDelete.tsx
Labels: Feat

#67 Feat: 여행지 이동 거리 및 이동 예상 시간 표시 기능
  src/assets/common/car-icon.png
  src/assets/test/diary-example.png
  src/components/survey/result/detail/SurveyKakaoMap.tsx
  src/components/survey/result/detail/SurveyPlaceItem.tsx
  src/components/tour/TourKakaoMap.tsx
  src/hooks/common/useKakaoNavi.ts
  src/libs/convertDistance.ts
  src/libs/convertDuration.ts
  src/types/kakaoNavi.ts
Labels: Feat, Remove

#68 Feat: 콘텐츠 검색 기능
  src/assets/common/search-icon.png
  src/components/diary/update/DiaryUpdateEditor.tsx
  src/components/mypage/MypageNicknameModal.tsx
  src/components/skeleton/survey/content/SurveyContentItemListSkeleton.tsx
  src/components/survey/content/SurveyContentItemList.tsx
  src/components/survey/content/SurveyContentSearchbar.tsx
  src/hooks/auth/useUserInfo.ts
  src/hooks/common/useDebounce.ts
  src/hooks/common/useThrottle.ts
  src/hooks/mypage/useNicknameModal.ts
  src/hooks/survey/content/useSurveyContentItemList.ts
  src/libs/zod/ContentTitleSchema.ts
  src/libs/zod/NicknameSchema.ts
  src/screens/diary/DiaryEditorScreen.tsx
  src/screens/survey/SurveyContentScreen.tsx
  src/types/survey.ts
Labels: Design, Feat, Fix

#69 Feat: 내 여행 계획 제목 변경 기능
  README.md
  src/components/diary/list/DiaryCardList.tsx
  src/components/survey/content/SurveyContentItemList.tsx
  src/components/tour/TourItem.tsx
  src/components/tour/TourItemList.tsx
  src/components/tour/TourItemMenu.tsx
  src/components/tour/TourItemTitleModal.tsx
  src/hooks/auth/useUserInfo.ts
  src/hooks/tour/useTourItemTitleUpdate.tsx
  src/libs/zod/TourItemTitleSchema.ts
  src/screens/auth/AuthScreen.tsx
Labels: Feat, Refactor

#70 Design: 발견 화면 UI 구현
  src/App.tsx
  src/components/discovery/DiscoveryDetail.tsx
  src/components/discovery/RecommendationDiscovery.tsx
  src/components/discovery/TopDiscoveryKeywordList.tsx
  src/components/stack/DiscoveryStack.tsx
  src/screens/DiscoveryScreen.tsx
  src/types/discovery.d.ts
  src/types/navigation.ts
  tailwind.config.js
Labels: Design
